<option value="">Select</option>
<option value="los">Murtala Muhammed International Airport, Lagos (LOS)</option>
<option value="sd">Nnamdi Azikiwe International Airport, Abuja (ABV)</option>
<option value="sj">Asaba International Airport, Asaba (ABB)</option>
<option value="ph">Port Bouet Airport, Abidjan (ABJ)</option>
<option value="nl">Kotoka International Airport, Accra (ACC)</option>
<option value="sf">Akure Airport, Akure (AKR)</option>
<option value="hu">Benin Airport, Benin (BNI)</option>
<option value="sa">Margaret Ekpo International Airport, Calabar (CBQ)</option>
<option value="hu">Benin Airport, Benin (BNI)</option>
<option value="sa">Ilorin International Airport, Ilorin (ILR)</option>
<option value="hu">Ibadan Airport, Ibadan (IBR)</option>
<option value="sa">Yakubu Gowon Airport, Jos (JOS)</option>
<option value="hu">Kaduna Airport, Kaduna (KAD)</option>
<option value="sa">Mallam Aminu International Airport, Kano (KAN)</option>
<option value="hu">Port Harcourt International Airport, Port Hartcourt (PHC)</option>
<option value="sa">Akwa Ibom International Airport, Uyo (QUO)</option>
<option value="hu">Cape Town International Airport, Cape Town (CPT)</option>
<option value="sa">Grand Central Airport, Johannesburg (JBN)</option>
<option value="hu">Jomo Kenyatta International Airport, Nairobi (NBO)</option>
<option value="sa">Cairo International Airport, Cairo (CAI)</option>
<option value="hu">Berlin-Schönefeld Airport, Berlin (SXF)</option>
<option value="sa">Frankfurt am Main Airport, Frankfurt (FRA)</option>
<option value="hu">Cologne Bonn Airport, Cologne (CGN)</option>
<option value="sa">Munich Airport, Munich (MUC)</option>
<option value="hu">Manchester Airport, Manchester (MAN)</option>
<option value="sa">Cardiff International Airport, Cardiff (CWL)</option>
<option value="hu">London Gatwick Airport, London (CGW)</option>
<option value="sa">London Heathrow Airport, London (LHR)</option>
<option value="hu">Newcastle Airport, Newcastle (NCL)</option>
<option value="sa">Brisbane Archerfield Airport, Brisbane (ACF)</option>
<option value="hu">Gold Coast Airport, Coolangatta (OOL)</option>
<option value="sa">Melbourne International Airport, Melbourne (MEL)</option>
<option value="hu">Buttonville Municipal Airport, Toronto (YKZ)</option>
<option value="sa">Windsor Airport, Windsor (YQG)</option>
<option value="hu">Hartsfield Jackson Atlanta International Airport, Atlanta (ATL)</option>
<option value="sa">Los Angeles International Airport, Los Angeles (LAX)</option>
<option value="hu">George Bush Intercontinental Houston Airport, Houston (IAH)</option>
<option value="sa">John F Kennedy International Airport, New York (JFK)</option>